### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by paulgessinger** [acts-project/traccc#32]
I know this is a bit pedantic, but I think there are a lot of whitespace changes in PRs that we don't really care about.

Are there objections to introducing clang-format to standardize formatting?

@beomki-yeo @stephenswat @krasznaa

**Comment by krasznaa** [comment]
I'm not against format checking in the CI. But I have to admit that I don't really like the formatting that the Acts code has. :frowning: I know that this is super subjective though. So a fixed formatting, even one that I would not necessarily use myself, is still better than no formatting guidelines at all...

At the very least it would be good to make everybody use spaces for tabs. :stuck_out_tongue: Since Beomki's latest updates looked very different in the GitHub PR than they did on my own machine in VS Code. (In the latter it looked reasonable. In the PR not so much.)

I've been wondering about introducing something for VecMem as well, I just never got around to setting it up. If you can give us a hand in that as well, that would be nice. :wink: (Though there I'll definitely want to tweak the formatting rules a bit to my own liking. :stuck_out_tongue:)

**Comment by paulgessinger** [comment]
Formatting creates the fiercest battles in programming 😛. I also have opinions on formatting, but I honestly care whichever format style is used as long as it's consistent.

For ACTS I just tried to go with the Google style with as few modifications as possible. For traccc and vecmem I would suggest we pick one of the default clang-format setups, give that a shot, and tweak as little as possible if we find it necessary.

I can set this up for traccc and vecmem.

**Comment by stephenswat** [comment]
Personally I really don't care for automatic formatting tools, but that's probably because I prefer a rather unorthodox style in many ways. In any case, I'll adapt to whatever is put in, even if it might not be my personal preference. What would be ideal for me would be checks on white space, which is to say no trailing white space on lines and a newline at the end of the file. But I can work in the framework of more strict automatic formatting, too.

What I personally find far more important is keeping merge requests clean of unrelated (formatting) changes, it's always frustrating to me to see a simple ten-line merge request with a hundred lines of white space changes added by IDEs. This is why I would personally support a blanket ban on `git add` (without modifiers) and especially `git commit -a`. If we could all take the time to `git add -p` the world would be a better place. I say this mostly jokingly, and I haven't seen it run rampant in this project yet, but it does get on my nerves in other projects sometimes. :smile:

**Comment by paulgessinger** [comment]
I think the whitespace content of PRs goes down drastically just by virtue of having auto formatting. The only requirement for this is that everyone uses the same format rules, and enforce by CI. Then I can happily hit the IDE formatter (I have all my editors set to auto format on save), and it will just produce the canonical format.

**Comment by stephenswat** [comment]
That's true. It makes life somewhat harder for people not using an IDE, but if we can provide a good pre-commit hook that should be fine. Again, my preference would be to enforce only strict requirements on white space, but I am flexible.

**Comment by paulgessinger** [comment]
I believe clang-format removes trailing white space, for newline I'm not sure. We've had this pop up in ACTS here and there, but I wasn't able to make it reliable.

You can make vim autoformat on save too 😄. In the end you just run a small script that runs clang-format, and you have to make sure you have the correct clang-format version. Putting it in a pre-commit hook can't be enforced and would be up to you.

Overall we've had very good experiences with clang-format in ACTS main.

**Comment by beomki-yeo** [comment]
I have no objections in introducing CI format. ACTS formatting is not my preference as well, but I don't care much about it as well. Anyway its important to have it... :))))

**Comment by paulgessinger** [comment]
I'll make a PR for this tomorrow or early next week.

**Comment by stephenswat** [comment]
I feel like this issue has been resolved a while back with #39, so I'll close this.
